"""empty message

Revision ID: 03f7f723fb83
Revises: 7390e707b395
Create Date: 2024-03-18 14:20:34.668697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03f7f723fb83'
down_revision = '7390e707b395'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainers', schema=None) as batch_op:
        batch_op.drop_constraint('trainers_address_key', type_='unique')
        batch_op.drop_constraint('trainers_phone_number_key', type_='unique')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_address_key', type_='unique')
        batch_op.drop_constraint('users_phone_number_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('users_phone_number_key', ['phone_number'])
        batch_op.create_unique_constraint('users_address_key', ['address'])

    with op.batch_alter_table('trainers', schema=None) as batch_op:
        batch_op.create_unique_constraint('trainers_phone_number_key', ['phone_number'])
        batch_op.create_unique_constraint('trainers_address_key', ['address'])

    # ### end Alembic commands ###
