"""empty message

Revision ID: 61f62f75f5a9
Revises: 61ef68ffd714
Create Date: 2024-03-22 01:47:05.090097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61f62f75f5a9'
down_revision = '61ef68ffd714'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('administrators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_confirmed', sa.Boolean(), nullable=True))
        batch_op.drop_column('reset_token')

    with op.batch_alter_table('trainers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_confirmed', sa.Boolean(), nullable=True))
        batch_op.drop_column('reset_token')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_confirmed', sa.Boolean(), nullable=True))
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.drop_column('is_confirmed')

    with op.batch_alter_table('trainers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.drop_column('is_confirmed')

    with op.batch_alter_table('administrators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.drop_column('is_confirmed')

    # ### end Alembic commands ###
