"""empty message

Revision ID: 71dfe2fd4357
Revises: 
Create Date: 2024-03-13 18:52:03.256052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71dfe2fd4357'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('specializations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('logo_url'),
    sa.UniqueConstraint('name')
    )
    op.create_table('trainers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('website_url', sa.String(length=100), nullable=True),
    sa.Column('instagram_url', sa.String(length=100), nullable=True),
    sa.Column('facebook_url', sa.String(length=100), nullable=True),
    sa.Column('x_url', sa.String(length=100), nullable=True),
    sa.Column('certification', sa.String(length=255), nullable=False),
    sa.Column('bank_iban', sa.String(length=34), nullable=False),
    sa.Column('vote_user', sa.Integer(), nullable=True),
    sa.Column('sum_value', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('bank_iban'),
    sa.UniqueConstraint('certification'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('training_level', sa.Enum('Beginner', 'Intermediate', 'Advanced', name='training_level'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('trainers_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('training_type', sa.Integer(), nullable=True),
    sa.Column('training_level', sa.Enum('Beginner', 'Intermediate', 'Advanced', name='training_level'), nullable=False),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ),
    sa.ForeignKeyConstraint(['training_type'], ['specializations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('trainers_specializations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('specialization_id', sa.Integer(), nullable=True),
    sa.Column('trainer_id', sa.Integer(), nullable=True),
    sa.Column('certification', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('Requested', 'Approved', 'Rejected', name='status'), nullable=False),
    sa.ForeignKeyConstraint(['specialization_id'], ['specializations.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('certification')
    )
    op.create_table('users_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('stripe_status', sa.Enum('Cart', 'Paid', 'Reject', name='stripe_status'), nullable=False),
    sa.Column('trainer_status', sa.Enum('Paid', 'Pending', name=' trainer_status'), nullable=False),
    sa.Column('value', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['trainers_classes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_classes')
    op.drop_table('trainers_specializations')
    op.drop_table('trainers_classes')
    op.drop_table('users')
    op.drop_table('trainers')
    op.drop_table('specializations')
    op.drop_table('administrator')
    # ### end Alembic commands ###
