"""empty message

Revision ID: 9f67f8fb8970
Revises: ec4c61001b74
Create Date: 2024-03-14 18:25:41.904983

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9f67f8fb8970'
down_revision = 'ec4c61001b74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('administrator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    with op.batch_alter_table('specializations', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('logo_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_constraint('specializations_logo_url_key', type_='unique')

    with op.batch_alter_table('trainers', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('trainers_certification_key', type_='unique')
        batch_op.drop_column('certification')

    with op.batch_alter_table('trainers_classes', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('training_level',
               existing_type=postgresql.ENUM('Beginner', 'Intermediate', 'Advanced', name='training_level'),
               nullable=True)

    with op.batch_alter_table('trainers_specializations', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('Requested', 'Approved', 'Rejected', name='status'),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('training_level')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('training_level', postgresql.ENUM('Beginner', 'Intermediate', 'Advanced', name='training_level'), autoincrement=False, nullable=False))
        batch_op.alter_column('phone_number',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('trainers_specializations', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('Requested', 'Approved', 'Rejected', name='status'),
               nullable=False)

    with op.batch_alter_table('trainers_classes', schema=None) as batch_op:
        batch_op.alter_column('training_level',
               existing_type=postgresql.ENUM('Beginner', 'Intermediate', 'Advanced', name='training_level'),
               nullable=False)
        batch_op.alter_column('duration',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('trainers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('certification', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('trainers_certification_key', ['certification'])
        batch_op.alter_column('phone_number',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('specializations', schema=None) as batch_op:
        batch_op.create_unique_constraint('specializations_logo_url_key', ['logo_url'])
        batch_op.alter_column('logo_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)

    with op.batch_alter_table('administrator', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
